# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zm_nmf <- function(A, k, max_iter, rel_tol, n_threads, verbose, inner_max_iter, inner_rel_tol, trace, alpha) {
    .Call(`_zmNMF_zm_nmf`, A, k, max_iter, rel_tol, n_threads, verbose, inner_max_iter, inner_rel_tol, trace, alpha)
}

